services:
  couchdb:
    image: couchdb:latest
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    restart: always
    ports:
      - "5984:5984"
