services:
  hotspot:
    build: ./hotspot
    restart: always
    privileged: true
    network_mode: host
  web:
    build: ./web
    restart: always
    ports:
      - "80:80"
  couchdb:
    image: matthiasg/rpi-couchdb
    # image: couchdb:3.4
    volumes:
      - ./data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=password
    restart: always
    ports:
      - "5984:5984"
  couchdb-setup:
    image: curlimages/curl:latest
    depends_on:
      - couchdb
    volumes:
      - ./couchdb/init.sh:/init.sh
    command: sh /init.sh
    restart: "no"
