version: '2'
services:
  hotspot:
    build: ./hotspot
    privileged: true
    network_mode: host
  web:
    build: ./web
    ports:
      - "80:80"
  couchdb:
    image: matthiasg/rpi-couchdb
    ports:
      - "5984:5984"
